### ISSUE TITLE
Cannot restore files after restart/window reload

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-repositories-github#182]
Issue Type: <b>Bug</b>

This is what I get: 
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/4674940/161561582-1504771b-56e8-4c9b-8fed-54b379f71386.png">

`Try again` solves the problem.

```
[2022-04-04 07:03:36.222] [renderer1] [error] ENOPRO: No file system provider found for resource 'github://github/kieferrm/notes/planning-thoughts/2022-April.md'
    at u.withProvider (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:593:17660)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u.withReadProvider (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:593:17783)
    at async u.readFileStream (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:593:22834)
    at async m.doRead (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2671:42343)
    at async m.readStream (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2671:42018)
    at async tr.resolveFromFile (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2660:66688)
    at async doResolve (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2671:36878)
    at async Da.doResolveAsText (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2132:89317)
    at async Promise.all (index 0)
    at async Mr.createModel (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1727:18946)
    at async Mr.resolve (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1727:18661)
    at async qa.setInput (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2635:34932)
    at async i.doSetInput (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2635:26897)
    at async i.doOpenEditor (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2635:25270)
    at async i.openEditor (vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2635:24930)
    at async vscode-file://vscode-app/Users/kmaetzel/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2841:17260
[2022-04-04 07:03:37.319] [renderer1] [error] ENOENT: no such file or directory, scandir '/kieferrm/notes': Error: ENOENT: no such file or directory, scandir '/kieferrm/notes'
```

Extension version: 0.31.2022040402
VS Code version: Code - Insiders 1.67.0-insider (5467c8c4413be3a69960fe418d2c345bfbdf2b55, 2022-04-04T05:29:30.893Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 24, 12|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
pynewfile477:30451556

```

</details>

**Comment by joyceerhl** [comment]
I think I've seen this before when @TylerLeonhardt demoed something in Azure Repos. We must be leaking provider URIs somewhere.

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-remote-repositories-github/issues/180
