### ISSUE TITLE
Pre-release broken

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-remote-repositories-github#287]
Using

```
Name: Remote Repositories
Id: ms-vscode.remote-repositories
Description: Remotely browse and edit git repositories
Version: 0.27.2023012401
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-repositories
```

Seeing, 

```
notificationsAlerts.ts:40 TypeError: TelemetrySender.sendEventData must be a function
    at Function.validateSender (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:38355)
    at Object.createTelemetryLogger (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:31905)
    at new BaseTelemetryReporter (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/github.remotehub-0.48.0/dist/extension.js:25:2062)
    at new TelemetryReporter (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/github.remotehub-0.48.0/dist/extension.js:28:1158)
    at new _TelemetryService (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/github.remotehub-0.48.0/dist/extension.js:326:21044)
    at Object.registerVirtualProviderService (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/github.remotehub-0.48.0/dist/extension.js:826:4539)
    at vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/ms-vscode.remote-repositories-0.27.2023012401/dist/extension.js:405:10398
    at ensureProvidersRegistered (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/ms-vscode.remote-repositories-0.27.2023012401/dist/extension.js:405:10502)
    at openRepository (vscode-file://vscode-app/Users/jrieken/.vscode-insiders/extensions/ms-vscode.remote-repositories-0.27.2023012401/dist/extension.js:276:22608)
    at s.h (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108033)
```

**Comment by joyceerhl** [comment]
From the logs above you have stable GitHub Repositories v0.48.0. Switching to prerelease GitHub Repositories should resolve this error.
